/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

	resources: {
		简介: ['resources/resources-intro'],
		前端开发: ['resources/ui/css-frameworks/css-frameworks'],

		开发工具: ['resources/tools/vs-code-themes/vs-code-themes']
	},
	tools: {
		简介: ['tools/tools-intro'],
		'CSS 工具': ['tools/glassmorphism-generator/glassmorphism-generator']
	},
	front: {
		简介: ['front/front-intro'],
		JavaScript: [
			{
				type: 'autogenerated',
				dirName: 'front/js'
			}
		],
		CSS: [
			{
				type: 'autogenerated',
				dirName: 'front/css'
			}
		],
		HTML: [
			{
				type: 'autogenerated',
				dirName: 'front/html'
			}
		],
		实战项目: [
			{
				type: 'autogenerated',
				dirName: 'front/projects'
			}
		],
		特效: [
			{
				type: 'autogenerated',
				dirName: 'front/effects'
			}
		],
		浏览器: [
			{
				type: 'autogenerated',
				dirName: 'front/browser'
			}
		],
		网络: [
			{
				type: 'autogenerated',
				dirName: 'front/network'
			}
		],
		React: [
			{
				type: 'autogenerated',
				dirName: 'front/react'
			}
		],
		Vue: [
			{
				type: 'autogenerated',
				dirName: 'front/vue'
			}
		],
		TypeScript: [
			{
				type: 'autogenerated',
				dirName: 'front/ts'
			}
		]
	},
	back: {
		简介: ['back/back-intro'],
		Express: [
			{
				type: 'autogenerated',
				dirName: 'back/express'
			}
		],
		'Mongo DB': [
			{
				type: 'autogenerated',
				dirName: 'back/mongo'
			}
		]
	},
	algorithm: {
		简介: ['algorithm/algorithm-intro']
	}
}

module.exports = sidebars
